/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Mouli
 */
public class VistaConductores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaConductores.class.getName());

    /**
     * Creates new form VistaConductores
     */
    public VistaConductores() {
        initComponents();
        cargarConductores();
        setTitle("Gestión de Conductores");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        lblRut.setVisible(false);
        lblNombre.setVisible(false);
        lblApellido.setVisible(false);
        lblLicencia.setVisible(false);
        lblTelefono.setVisible(false);
        txtRut.setVisible(false);
        txtNombre.setVisible(false);
        txtApellido.setVisible(false);
        txtLicencia.setVisible(false);
        txtTelefono.setVisible(false);
        lblcamionesdisponibles.setVisible(false);
        jcamionesdisponibles.setVisible(false);
        btnasignar.setVisible(false);
        btnactualizar.setVisible(false);
    }
    
    private int idConductorSeleccionado = -1;
    
    private void mostrarFormulario(boolean esModificar) {
        lblRut.setVisible(true);
        lblNombre.setVisible(true);
        lblApellido.setVisible(true);
        lblLicencia.setVisible(true);
        lblTelefono.setVisible(true);
        txtRut.setVisible(true);
        txtNombre.setVisible(true);
        txtApellido.setVisible(true);
        txtLicencia.setVisible(true);
        txtTelefono.setVisible(true); 

        btnactualizar.setVisible(true);

        if (!esModificar) {
            txtRut.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtLicencia.setText("");
            txtTelefono.setText("");
        }
    }
    
    private void cargarConductores() {
        Dao.ConductorDao dao = new Dao.ConductorDao();

        java.util.List<modelo.Conductor> lista = dao.listarConductores();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (modelo.Conductor co : lista) {
            model.addRow(new Object[]{
                co.getId_conductor(),
                co.getRut(),
                co.getNombre(),
                co.getApellido(),
                co.getTipo_licencia(),
                co.getTelefono(),
                co.getId_camion()
            });
        }
    }
    
    private void guardarConductor() {
        try {
            modelo.Conductor conductor = new modelo.Conductor();

            conductor.setRut(txtRut.getText());
            conductor.setNombre(txtNombre.getText());
            conductor.setApellido(txtApellido.getText());
            conductor.setTipo_licencia(txtLicencia.getText());
            conductor.setTelefono(txtTelefono.getText());

            Dao.ConductorDao dao = new Dao.ConductorDao();

            boolean resultado;

            if (idConductorSeleccionado != -1) {
                // MODIFICAR
                conductor.setId_conductor(idConductorSeleccionado);
                resultado = dao.modificarConductor(conductor);
            } else {
                // AGREGAR
                resultado = dao.agregarConductor(conductor);
            }

            if (resultado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Operación exitosa");
                cargarConductores();

                idConductorSeleccionado = -1;
                btnactualizar.setText("Guardar");

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error en la operación");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Datos inválidos");
        }
    }
    private void cargarCamionesCombo() {
        lblcamionesdisponibles.setVisible(true);
        jcamionesdisponibles.setVisible(true);
        btnasignar.setVisible(true);
        jcamionesdisponibles.removeAllItems();

        Dao.CamionesDao dao = new Dao.CamionesDao();
        java.util.List<modelo.Camion> lista = dao.listarCamiones(null, null, null, null, null);

        for (modelo.Camion c : lista) {
            jcamionesdisponibles.addItem(c.getId_camion() + " - " + c.getPatente());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblLicencia = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        btnagregarconductor = new javax.swing.JButton();
        btnmodificarconductor = new javax.swing.JButton();
        btnasignarcamion = new javax.swing.JButton();
        btneliminarcamion = new javax.swing.JButton();
        lblcamionesdisponibles = new javax.swing.JLabel();
        jcamionesdisponibles = new javax.swing.JComboBox<>();
        btnasignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RUT", "Nombre", "Apellido", "Licencia", "Telefono", "Camión Asignado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblTelefono.setText("Telefono");

        lblRut.setText("RUT");

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblLicencia.setText("Licencia");

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnagregarconductor.setText("Agregar Conductor");
        btnagregarconductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarconductorActionPerformed(evt);
            }
        });

        btnmodificarconductor.setText("Modificar Conductor");
        btnmodificarconductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarconductorActionPerformed(evt);
            }
        });

        btnasignarcamion.setText("Asignar camión");
        btnasignarcamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignarcamionActionPerformed(evt);
            }
        });

        btneliminarcamion.setText("Eliminar Conductor");
        btneliminarcamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarcamionActionPerformed(evt);
            }
        });

        lblcamionesdisponibles.setText("Camiones disponibles");

        jcamionesdisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnasignar.setText("Asignar");
        btnasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnasignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblRut)
                            .addComponent(lblApellido)
                            .addComponent(lblLicencia)
                            .addComponent(lblTelefono)
                            .addComponent(lblcamionesdisponibles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLicencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcamionesdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnasignar)
                            .addComponent(btnactualizar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnagregarconductor)
                .addGap(18, 18, 18)
                .addComponent(btnmodificarconductor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnasignarcamion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminarcamion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnagregarconductor)
                            .addComponent(btnmodificarconductor)
                            .addComponent(btnasignarcamion)
                            .addComponent(btneliminarcamion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicencia)
                            .addComponent(txtLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnactualizar)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcamionesdisponibles)
                            .addComponent(jcamionesdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnasignar)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        guardarConductor();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnagregarconductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarconductorActionPerformed
       idConductorSeleccionado = -1;
       mostrarFormulario(false);
       btnactualizar.setText("Agregar Camión");
    }//GEN-LAST:event_btnagregarconductorActionPerformed

    private void btnasignarcamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignarcamionActionPerformed
        cargarCamionesCombo();
    }//GEN-LAST:event_btnasignarcamionActionPerformed

    private void btnasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnasignarActionPerformed
       int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un conductor");
            return;
        }

        int idConductor = (int) jTable1.getValueAt(fila, 0);

        // Obtener ID del camión desde el combo
        String seleccionado = jcamionesdisponibles.getSelectedItem().toString();
        int idCamion = Integer.parseInt(seleccionado.split(" - ")[0]);

        Dao.ConductorDao dao = new Dao.ConductorDao();
        boolean resultado = dao.asignarCamion(idConductor, idCamion);

        if (resultado) {
            javax.swing.JOptionPane.showMessageDialog(this, "Camión asignado correctamente");
            cargarConductores();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al asignar camión");
        }
        lblcamionesdisponibles.setVisible(false);
        jcamionesdisponibles.setVisible(false);
        btnasignar.setVisible(false);
    }//GEN-LAST:event_btnasignarActionPerformed

    private void btnmodificarconductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarconductorActionPerformed
       int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un camión primero");
            return;
        }

        idConductorSeleccionado = (int) jTable1.getValueAt(fila, 0);

        mostrarFormulario(true);

        txtRut.setText(jTable1.getValueAt(fila, 1).toString());
        txtNombre.setText(jTable1.getValueAt(fila, 2).toString());
        txtApellido.setText(jTable1.getValueAt(fila, 3).toString());
        txtLicencia.setText(jTable1.getValueAt(fila, 4).toString());
        txtTelefono.setText(jTable1.getValueAt(fila, 5).toString());

        btnactualizar.setText("Guardar Cambios");
    }//GEN-LAST:event_btnmodificarconductorActionPerformed

    private void btneliminarcamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarcamionActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un conductor primero");
            return;
        }

        int id = (int) jTable1.getValueAt(fila, 0);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres eliminar este conductor?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        Dao.ConductorDao dao = new Dao.ConductorDao();

        if (dao.eliminarConductor(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Conductor eliminado correctamente");
            cargarConductores();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el camión");
        }
    }//GEN-LAST:event_btneliminarcamionActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregarconductor;
    private javax.swing.JButton btnasignar;
    private javax.swing.JButton btnasignarcamion;
    private javax.swing.JButton btneliminarcamion;
    private javax.swing.JButton btnmodificarconductor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcamionesdisponibles;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblcamionesdisponibles;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
