/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Santo Tomas
 */

public class VistaCamiones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCamiones.class.getName());

    /**
     * Creates new form VistaCamiones
     */
    public VistaCamiones() {
        initComponents();
        setTitle("Gestión de Camiones");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        RenderAlertaMantenimiento render = new RenderAlertaMantenimiento();
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(render);
            cargarCamiones();
        }
    }
    private int idCamionSeleccionado = -1;

    private void cargarCamiones() {
        Dao.CamionesDao dao = new Dao.CamionesDao();
        // Ahora esta línea ya no dará error porque el DAO reconoce los 5 parámetros
        java.util.List<modelo.Camion> lista = dao.listarCamiones(null, null, null, null, null);

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (modelo.Camion c : lista) {
            model.addRow(new Object[]{
                c.getId_camion(),
                c.getPatente(),
                c.getMarca(),
                c.getModelo(),
                c.getAnio(),
                c.getKilometro_acumulado(),
                c.getEstado()
            });
        }
    }
    // Renderizador personalizado para resaltar alertas de mantenimiento

    class RenderAlertaMantenimiento extends javax.swing.table.DefaultTableCellRenderer {

        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // Obtenemos el kilometraje de la columna índice 5 (Kilometros Acumulado)
            try {
                float km = Float.parseFloat(table.getValueAt(row, 5).toString());

                if (km >= 5000) {
                    c.setBackground(new java.awt.Color(255, 51, 51)); // Rojo para alerta
                    c.setForeground(java.awt.Color.WHITE); // Texto blanco para que se lea bien
                } else {
                    // Volver a los colores oscuros de tu interfaz original
                    c.setBackground(new java.awt.Color(33, 32, 35));
                    c.setForeground(java.awt.Color.WHITE);
                }
            } catch (Exception e) {
                // En caso de error, mantener colores por defecto
            }

            // Si la fila está seleccionada, mantener el color de selección del sistema
            if (isSelected) {
                c.setBackground(table.getSelectionBackground());
                c.setForeground(table.getSelectionForeground());
            }

            return c;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMantenimiento = new javax.swing.JButton();
        btn_modificarcamion = new javax.swing.JButton();
        btn_agregarcamiones = new javax.swing.JButton();
        btn_eliminarcamion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMantenimiento.setBackground(new java.awt.Color(125, 106, 140));
        btnMantenimiento.setText("Mantenimiento");
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 120, -1));

        btn_modificarcamion.setBackground(new java.awt.Color(125, 106, 140));
        btn_modificarcamion.setText("Modificar Camión");
        btn_modificarcamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarcamionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificarcamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        btn_agregarcamiones.setBackground(new java.awt.Color(125, 106, 140));
        btn_agregarcamiones.setText("Agregar Camión");
        btn_agregarcamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcamionesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarcamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        btn_eliminarcamion.setBackground(new java.awt.Color(125, 106, 140));
        btn_eliminarcamion.setText("Eliminar Camión");
        btn_eliminarcamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarcamionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminarcamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, -1, -1));

        jTable1.setBackground(new java.awt.Color(33, 32, 35));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Patente", "Marca", "Modelo", "Año", "Kilometros Acumulado", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 790, 499));

        btn_volver.setBackground(new java.awt.Color(125, 106, 140));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FONDOAHORASI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarcamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarcamionActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un camión primero");
            return;
        }

        int id = (int) jTable1.getValueAt(fila, 0);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres eliminar este camión?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        Dao.CamionesDao dao = new Dao.CamionesDao();

        if (dao.eliminarCamion(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Camión eliminado correctamente");
            cargarCamiones();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el camión");
        }
    }//GEN-LAST:event_btn_eliminarcamionActionPerformed

    private void btn_agregarcamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcamionesActionPerformed
        FormCamiones form = new FormCamiones(this, true, null); // null indica nuevo
        form.setVisible(true);
        cargarCamiones();
    }//GEN-LAST:event_btn_agregarcamionesActionPerformed

    private void btn_modificarcamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarcamionActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un camión");
            return;
        }

        // Crear objeto Camion con los datos de la fila seleccionada
        modelo.Camion seleccionado = new modelo.Camion(
                (int) jTable1.getValueAt(fila, 0), // id
                jTable1.getValueAt(fila, 1).toString(), // patente
                jTable1.getValueAt(fila, 2).toString(), // marca
                jTable1.getValueAt(fila, 3).toString(), // modelo
                (int) jTable1.getValueAt(fila, 4), // anio
                (float) jTable1.getValueAt(fila, 5), // kilometraje
                modelo.Camion.Estado.valueOf(jTable1.getValueAt(fila, 6).toString()) // estado
        );

        FormCamiones form = new FormCamiones(this, true, seleccionado);
        form.setVisible(true);
        cargarCamiones(); // Refrescar tabla

    }//GEN-LAST:event_btn_modificarcamionActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        VistaMenuPrincipal vista = new VistaMenuPrincipal();
        vista.setVisible(true);
        this.dispose();
        vista.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            // Sacamos el ID y la Patente de la fila seleccionada
            int idCamion = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
            String patente = jTable1.getValueAt(fila, 1).toString();

            // Abrimos el formulario pasando esos datos
            FormMantenimiento fm = new FormMantenimiento(this, true, idCamion, patente);
            fm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un camión de la tabla primero");
        }
    
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btn_agregarcamiones;
    private javax.swing.JButton btn_eliminarcamion;
    private javax.swing.JButton btn_modificarcamion;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
