/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Mouli
 */
public class VistaConductores extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaConductores.class.getName());

    /**
     * Creates new form VistaConductores
     */
    public VistaConductores() {
        initComponents();
        cargarConductores();
        setTitle("Gestión de Conductores");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarConductores();
    }

    private int idConductorSeleccionado = -1;

    private void cargarConductores() {
        Dao.ConductorDao dao = new Dao.ConductorDao();
        java.util.List<modelo.Conductor> lista = dao.listarConductores();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (modelo.Conductor co : lista) {
            model.addRow(new Object[]{
                co.getId_conductor(),
                co.getRut(),
                co.getNombre(),
                co.getApellido(),
                co.getTipo_licencia(),
                co.getTelefono(),
                co.getId_camion() == 0 ? "Sin asignar" : co.getId_camion() // Mejora visual
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnagregarconductor = new javax.swing.JButton();
        btnmodificarconductor = new javax.swing.JButton();
        btneliminarcamion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "RUT", "Nombre", "Apellido", "Licencia", "Telefono", "Camión Asignado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 770, 480));

        btnagregarconductor.setText("Agregar Conductor");
        btnagregarconductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarconductorActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregarconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        btnmodificarconductor.setText("Modificar Conductor");
        btnmodificarconductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarconductorActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificarconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));

        btneliminarcamion.setText("Eliminar Conductor");
        btneliminarcamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarcamionActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminarcamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondoo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarconductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarconductorActionPerformed
        FormConductores form = new FormConductores(this, true, null);
        form.setVisible(true);
        cargarConductores();
    }//GEN-LAST:event_btnagregarconductorActionPerformed

    private void btnmodificarconductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarconductorActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un conductor");
            return;
        }

        // Crear el objeto con los datos de la fila
        modelo.Conductor seleccionado = new modelo.Conductor(
                (int) jTable1.getValueAt(fila, 0), // ID
                jTable1.getValueAt(fila, 1).toString(), // RUT
                jTable1.getValueAt(fila, 2).toString(), // Nombre
                jTable1.getValueAt(fila, 3).toString(), // Apellido
                jTable1.getValueAt(fila, 4).toString(), // Licencia
                jTable1.getValueAt(fila, 5).toString(), // Telefono
                0 // ID Camión (puedes dejarlo en 0 si no se edita aquí)
        );

        // Llamada al formulario (ahora los parámetros coinciden)
        FormConductores form = new FormConductores(this, true, seleccionado);
        form.setVisible(true);

        cargarConductores(); // Refrescar la tabla al cerrar
    }//GEN-LAST:event_btnmodificarconductorActionPerformed

    private void btneliminarcamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarcamionActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un conductor primero");
            return;
        }

        int id = (int) jTable1.getValueAt(fila, 0);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres eliminar este conductor?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        Dao.ConductorDao dao = new Dao.ConductorDao();

        if (dao.eliminarConductor(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Conductor eliminado correctamente");
            cargarConductores();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el camión");
        }
    }//GEN-LAST:event_btneliminarcamionActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        VistaMenuPrincipal vista = new VistaMenuPrincipal();
        vista.setVisible(true);
        this.dispose();
        vista.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_volver;
    private javax.swing.JButton btnagregarconductor;
    private javax.swing.JButton btneliminarcamion;
    private javax.swing.JButton btnmodificarconductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
