/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Santo Tomas
 */
public class VistaCamiones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCamiones.class.getName());

    /**
     * Creates new form VistaCamiones
     */
    public VistaCamiones() {
        initComponents();
        cestado.removeAllItems();
        cestado.addItem("Disponible");
        cestado.addItem("Mantenimiento");
        cargarCamiones();
        setTitle("Gestión de Camiones");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jpatente.setVisible(false);
        jmarca.setVisible(false);
        jmodelo.setVisible(false);
        janio.setVisible(false);
        jkilometros.setVisible(false);
        txtpatente.setVisible(false);
        txtmarca.setVisible(false);
        txtmodelo.setVisible(false);
        txtanio.setVisible(false);
        txtkilometros.setVisible(false);
        btnactualizar.setVisible(false);
        cestado.setVisible(false);
        jestado.setVisible(false);
    }
    private int idCamionSeleccionado = -1;

    private void mostrarFormulario(boolean esModificar) {
        jpatente.setVisible(true);
        jmarca.setVisible(true);
        jmodelo.setVisible(true);
        janio.setVisible(true);

        txtpatente.setVisible(true);
        txtmarca.setVisible(true);
        txtmodelo.setVisible(true);
        txtanio.setVisible(true);

        // SOLO en modificar
        jkilometros.setVisible(esModificar);
        txtkilometros.setVisible(esModificar);

        // Estado solo en modificar
        cestado.setVisible(esModificar);
        jestado.setVisible(esModificar); // label "Estado"

        btnactualizar.setVisible(true);

        if (!esModificar) {
            txtpatente.setText("");
            txtmarca.setText("");
            txtmodelo.setText("");
            txtanio.setText("");
            txtkilometros.setText("");
        }
    }

    private void cargarCamiones() {
        Dao.CamionesDao dao = new Dao.CamionesDao();

        java.util.List<modelo.Camion> lista = dao.listarCamiones(null, null, null, null, null);
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (modelo.Camion c : lista) {
            model.addRow(new Object[]{
                c.getId_camion(),
                c.getPatente(),
                c.getMarca(),
                c.getModelo(),
                c.getAnio(),
                c.getKilometro_acumulado(),
                c.getEstado()
            });
        }
    }

    private void guardarCamion() {
        try {
            modelo.Camion camion = new modelo.Camion();

            camion.setPatente(txtpatente.getText());
            camion.setMarca(txtmarca.getText());
            camion.setModelo(txtmodelo.getText());
            camion.setAnio(Integer.parseInt(txtanio.getText()));

            camion.setEstado(modelo.Camion.Estado.valueOf(cestado.getSelectedItem().toString()));

            Dao.CamionesDao dao = new Dao.CamionesDao();

            boolean resultado;

            if (idCamionSeleccionado != -1) {
                // MODIFICAR
                camion.setId_camion(idCamionSeleccionado);
                camion.setKilometro_acumulado(Float.parseFloat(txtkilometros.getText()));

                resultado = dao.modificarCamion(camion);
            } else {
                // AGREGAR
                resultado = dao.agregarCamion(camion);
            }

            if (resultado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Operación exitosa");
                cargarCamiones();

                idCamionSeleccionado = -1;
                btnactualizar.setText("Actualizar");

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error en la operación");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Datos inválidos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_modificarcamion = new javax.swing.JButton();
        btn_agregarcamiones = new javax.swing.JButton();
        btn_eliminarcamion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpatente = new javax.swing.JLabel();
        jmarca = new javax.swing.JLabel();
        jmodelo = new javax.swing.JLabel();
        janio = new javax.swing.JLabel();
        jkilometros = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        txtpatente = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtanio = new javax.swing.JTextField();
        txtkilometros = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        cestado = new javax.swing.JComboBox<>();
        jestado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_modificarcamion.setText("Modificar Camión");
        btn_modificarcamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarcamionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificarcamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 573, -1, -1));

        btn_agregarcamiones.setText("Agregar Camión");
        btn_agregarcamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcamionesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarcamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 573, -1, -1));

        btn_eliminarcamion.setText("Eliminar Camión");
        btn_eliminarcamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarcamionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminarcamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 573, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Patente", "Marca", "Modelo", "Año", "Kilometros Acumulado", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 700, 499));

        jpatente.setText("Patente");
        getContentPane().add(jpatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, -1, -1));

        jmarca.setText("Marca");
        getContentPane().add(jmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, -1, -1));

        jmodelo.setText("Modelo");
        getContentPane().add(jmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 190, -1, -1));

        janio.setText("Año");
        getContentPane().add(janio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, -1, -1));

        jkilometros.setText("Kilometros Acumulados");
        getContentPane().add(jkilometros, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, -1));
        getContentPane().add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 150, -1));
        getContentPane().add(txtpatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 150, -1));
        getContentPane().add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 150, -1));
        getContentPane().add(txtanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 230, 150, -1));
        getContentPane().add(txtkilometros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, 150, -1));

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, -1, -1));

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1222, 6, -1, -1));

        cestado.setEditable(true);
        cestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, 150, -1));

        jestado.setText("Estado");
        getContentPane().add(jestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarcamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarcamionActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un camión primero");
            return;
        }

        int id = (int) jTable1.getValueAt(fila, 0);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres eliminar este camión?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        Dao.CamionesDao dao = new Dao.CamionesDao();

        if (dao.eliminarCamion(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Camión eliminado correctamente");
            cargarCamiones();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el camión");
        }
    }//GEN-LAST:event_btn_eliminarcamionActionPerformed

    private void btn_agregarcamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcamionesActionPerformed
        idCamionSeleccionado = -1;
        mostrarFormulario(false);
        btnactualizar.setText("Agregar Camión");
    }//GEN-LAST:event_btn_agregarcamionesActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        guardarCamion();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btn_modificarcamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarcamionActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un camión primero");
            return;
        }

        idCamionSeleccionado = (int) jTable1.getValueAt(fila, 0);

        mostrarFormulario(true);

        txtpatente.setText(jTable1.getValueAt(fila, 1).toString());
        txtmarca.setText(jTable1.getValueAt(fila, 2).toString());
        txtmodelo.setText(jTable1.getValueAt(fila, 3).toString());
        txtanio.setText(jTable1.getValueAt(fila, 4).toString());
        txtkilometros.setText(jTable1.getValueAt(fila, 5).toString());

        btnactualizar.setText("Guardar Cambios");
    }//GEN-LAST:event_btn_modificarcamionActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        VistaMenuPrincipal vista = new VistaMenuPrincipal();
        vista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarcamiones;
    private javax.swing.JButton btn_eliminarcamion;
    private javax.swing.JButton btn_modificarcamion;
    private javax.swing.JButton btn_volver;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JComboBox<String> cestado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel janio;
    private javax.swing.JLabel jestado;
    private javax.swing.JLabel jkilometros;
    private javax.swing.JLabel jmarca;
    private javax.swing.JLabel jmodelo;
    private javax.swing.JLabel jpatente;
    private javax.swing.JTextField txtanio;
    private javax.swing.JTextField txtkilometros;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtpatente;
    // End of variables declaration//GEN-END:variables
}
